data:
  test_size: 0.25
  random_state: 42
  stratify: true

model:
  name: "XGBoost"
  objective: "multi:softprob"
  eval_metric: "mlogloss"
  num_class: 7
  random_state: 42

training:
  n_iter: 20
  cv: 3
  scoring: "accuracy"
  n_jobs: -1

paths:
  data: "data/covtype.csv"
  model: "models/best_model.pkl"
  results: "results/"